name: davidho
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83604
title: just another site.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.17970372317358851
  lightness: 0.8812543102540076
  saturation: 0.9640551866032183
  rhythmicContrast: 0.3367126048542559
purpose: []
